<a href="https://colab.research.google.com/github/HarikaKirlampalli/Data-Analytics-Journey/blob/main/DA_Practice_Daily_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
num_=int(input())
if num_%2==0:
   print("prime")
else :
   print("Not Prime")

25
Not Prime

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
print("pandas imported")

pandas imported

In [ ]:
#creating Series('S' always be capital in Series)
data = [1,2,3,4]
s=pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
#creating user defined index
data = [1,2,3,4,5]
i = ['a','b','c','d','e']
s = pd.Series(data, index = i)
print(s)
#updating
s['a']=10
print(s)
#inserting new element(use directly or use concat)
s['f']=20
print(s)
#To remove element(drop method)
s = s.drop('a')
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    10
b     2
c     3
d     4
e     5
dtype: int64
a    10
b     2
c     3
d     4
e     5
f    20
dtype: int64
b     2
c     3
d     4
e     5
f    20
dtype: int64

In [ ]:
#creating series from dict
s2 = pd.Series({'x':100, 'y':200, 'z':300})
print(s2)

x    100
y    200
z    300
dtype: int64

In [ ]:
#Accessing
print(s2[0])
print(s2[0:2])
print(s2[1:])
print(s2[:2])

100
x    100
y    200
dtype: int64
y    200
z    300
dtype: int64
x    100
y    200
dtype: int64

/tmp/ipykernel_3418/4271714520.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s2[0])

In [ ]:
#creating a pandas series
marks = [78,85,92,67,88]
i= [101,102,103,104,105]
s=pd.Series(marks,index=i)
print(s)
#display the marks of 103
print(s[103])
#change the marks of 104 from 67 to 75
s[104]=75
print(s)
#delete 102
s=s.drop(102)
print(s)
#add 106 as 96
s[106]=96
print(s)

101    78
102    85
103    92
104    67
105    88
dtype: int64
92
101    78
102    85
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
106    96
dtype: int64

In [ ]:
import pandas as pd
# creating a pandas series
temperature = [30, 31, 29, 28, 32, 33, 31]
i = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
s = pd.Series(temperature, index=i)
print(s)
# display the temperature from Monday to Wednesday
print(s["Monday":"Wednesday"])
# change Thursday's temperature to 32
s["Thursday"] = 32
print(s)
# delete Saturday's temperature
s = s.drop("Saturday")
print(s)
# add Monday of next week as 30
s["Next Monday"] = 30
print(s)

Monday       30
Tuesday      31
Wednesday    29
Thursday     28
Friday       32
Saturday     33
Sunday       31
dtype: int64
Monday       30
Tuesday      31
Wednesday    29
dtype: int64
Monday       30
Tuesday      31
Wednesday    29
Thursday     32
Friday       32
Saturday     33
Sunday       31
dtype: int64
Monday       30
Tuesday      31
Wednesday    29
Thursday     32
Friday       32
Sunday       31
dtype: int64
Monday         30
Tuesday        31
Wednesday      29
Thursday       32
Friday         32
Sunday         31
Next Monday    30
dtype: int64

In [ ]:
import pandas as pd
# creating a pandas series
salary = [35000, 42000, 38000, 50000, 45000]
i = [1001, 1002, 1003, 1004, 1005]
s = pd.Series(salary, index=i)
print(s)
# change the salary of 1003 to 40000
s[1003] = 40000
print(s)
# delete 1002
s = s.drop(1002)
print(s)
# add 1006 as 55000
s[1006] = 55000
print(s)
# display the first 3 employees
print(s.head(3))

1001    35000
1002    42000
1003    38000
1004    50000
1005    45000
dtype: int64
1001    35000
1002    42000
1003    40000
1004    50000
1005    45000
dtype: int64
1001    35000
1003    40000
1004    50000
1005    45000
dtype: int64
1001    35000
1003    40000
1004    50000
1005    45000
1006    55000
dtype: int64
1001    35000
1003    40000
1004    50000
dtype: int64

In [ ]:
import pandas as pd
# creating a pandas series
price = [500, 750, 1200, 900, 1500]
i = ["P101", "P102", "P103", "P104", "P105"]
s = pd.Series(price, index=i)
print(s)
# display the price of P103
print(s["P103"])
# change the price of P102 to 800
s["P102"] = 800
print(s)
# delete P104
s = s.drop("P104")
print(s)
# add P106 as 2000
s["P106"] = 2000
print(s)

P101     500
P102     750
P103    1200
P104     900
P105    1500
dtype: int64
1200
P101     500
P102     800
P103    1200
P104     900
P105    1500
dtype: int64
P101     500
P102     800
P103    1200
P105    1500
dtype: int64
P101     500
P102     800
P103    1200
P105    1500
P106    2000
dtype: int64

In [ ]:
#Day-3 -viewing data
import pandas as pd
s= pd.Series(
    [5000,7000,6000,9000,8000],
  index=['monday','tuesday','wednesday','thursday','friday',])
print(s)

monday       5000
tuesday      7000
wednesday    6000
thursday     9000
friday       8000
dtype: int64

In [ ]:
print(s.head(2))

monday     5000
tuesday    7000
dtype: int64

In [ ]:
print(s.tail(2)) # it gives

thursday    9000
friday      8000
dtype: int64

In [ ]:
len(s) #

5

In [ ]:
s.shape # length and coma(,) describes it is 1-d

(5,)

In [ ]:
s.index #to see all the indexes

Index(['monday', 'tuesday', 'wednesday', 'thursday', 'friday'], dtype='object')

In [ ]:
s.values #to see all the values

array([5000, 7000, 6000, 9000, 8000])

In [ ]:
#Filtering means to see something specifically
s['monday']

np.int64(5000)

In [ ]:
s[['monday','friday']] # use list to see two index values

monday    5000
friday    8000
dtype: int64

In [ ]:
#filtring using a condition
print(s>6000) # codition to check normally

monday       False
tuesday       True
wednesday    False
thursday      True
friday        True
dtype: bool

In [ ]:
print(s[s>6000]) #codintion to check values other than boolean values

tuesday     7000
thursday    9000
friday      8000
dtype: int64

In [ ]:
#Cleaning data
#1.Missing Values (->identifying->counting->filling with zero or something or remove)
# Missing values are identified by NaN(Not a Number)
s=pd.Series([5000,7000,None,9000,None])
print(s)

0    5000.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64

In [ ]:
# isna() is a method to identify the missing values which reflects the boolean values
s.isna()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [ ]:
#sum is the method used to count missing values count
s.isna().sum()

np.int64(2)

In [ ]:
#use fillna() method to fill the missing values with something value like 0
s.fillna(0)

0    5000.0
1    7000.0
2       0.0
3    9000.0
4       0.0
dtype: float64

In [ ]:
s.fillna('ab') #for alphabet characters

0    5000.0
1    7000.0
2        ab
3    9000.0
4        ab
dtype: object

In [ ]:
#use dropna() method to drop the missing values
import pandas as pd
s=pd.Series([5000,7000,None,9000,None])
print(s)
s.dropna()

0    5000.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64

0    5000.0
1    7000.0
3    9000.0
dtype: float64

In [ ]:
#replace
s.replace(5000,5500)

0    5500.0
1    7000.0
2       NaN
3    9000.0
4       NaN
dtype: float64

In [ ]:
#Note : if use s.replace , s. drop like this means it will changes only temporarily....for example we want to change perminantely use s=s.replace , s=s.drop

In [ ]:
#DATAFRAMES - 2D
#Here we cannot follow index numbers for set so we have to change the set to list and then perform operation
#creating DataFrame with list
import pandas as pd
data=[
    ["Harika",22,35000],
    ("Priya",25,30000),
    ["Darshini",23,40000]
]
df = pd.DataFrame(data)
print(df)

          0   1      2
0    Harika  22  35000
1     Priya  25  30000
2  Darshini  23  40000

In [ ]:
#creating DataFrame with using tuple
import pandas as pd
data = (("Raju",27,32000),
        ("Kiran",25,35000),
        ("Priya",23,40000))
df=pd.DataFrame(data)
print(df)

       0   1      2
0   Raju  27  32000
1  Kiran  25  35000
2  Priya  23  40000

In [ ]:
#creating DataFrame Using set
my_set={100,200,250,300}
df_from_set=pd.DataFrame(
    list(my_set)
)
print(df_from_set)

     0
0  200
1  250
2  100
3  300

In [ ]:
#creating DataFrame Using Dictionary
data= {
    'Name' : ['Siddu','Thara','Gowtham'],
    'Age' : [25,22,30],
    'City' : ['HYD','VIZ','VZM']
}
df = pd.DataFrame(data)
print(df)

      Name  Age City
0    Siddu   25  HYD
1    Thara   22  VIZ
2  Gowtham   30  VZM

In [ ]:
#Converting Series to dataframe use to_frame() method
s=pd.Series(
    [1,2,3,4],
    name='Numbers'
)
df = s.to_frame()
print(df)

   Numbers
0        1
1        2
2        3
3        4

In [ ]:
s=pd.Series(
    [1,2,3,4],
    name='Numbers'
s2=pd.Series([6,7,8,9]),
s3=pd.Series([2,3,1,5])
)

df = s.to_frame()
df = s.to_frame()
df = s.to_frame()
print(df)

   Numbers
0        1
1        2
2        3
3        4

In [ ]:
#create dataframe using list of 5 students with a 3 subject marks
import pandas as pd
data={'English':[95,89,92,82,75],
      'Maths':[82,92,72,67,87],
      'Physics':[90,87,95,82,95]}
students=("Ajay","Rohit","Rahul","Kiran","Raju")
df=pd.DataFrame(data,index=students)
print(df)
#create a dataframe the sales and a profit of week using tuple
import pandas as pd
data = [("Monday", 1500, 400),
        ("Tuesday", 800, -50),
        ("Wednesday", 1600, 400),
        ("Thursday", 900, -120),
        ("Friday", 4000, 550),
        ("Saturday", 3500, 800),
        ("Sunday", 1500, 400)]
df = pd.DataFrame(data, columns=["Day", "Sales", "Profit_Loss"])
print(df)
#create a DF using dictionary
import pandas as pd
data={'Name':["pravallika","deepika","charan","hasini","Mamatha"],
      'Total_days':[30,30,30,30,30],
      'Days_present':[28,25,22,24,25],
      'Days_absent':[2,5,7,6,5]}
pf=pd.DataFrame(data)
print(pf)

       English  Maths  Physics
Ajay        95     82       90
Rohit       89     92       87
Rahul       92     72       95
Kiran       82     67       82
Raju        75     87       95
         Day  Sales  Profit_Loss
0     Monday   1500          400
1    Tuesday    800          -50
2  Wednesday   1600          400
3   Thursday    900         -120
4     Friday   4000          550
5   Saturday   3500          800
6     Sunday   1500          400
         Name  Total_days  Days_present  Days_absent
0  pravallika          30            28            2
1     deepika          30            25            5
2      charan          30            22            7
3      hasini          30            24            6
4     Mamatha          30            25            5

In [ ]:
#DAY-4 (iloc, loc)
import pandas as pd
s= pd.Series(
    [5000,7000,6000,9000,8000],
  index=['monday','tuesday','wednesday','thursday','friday',])
print(s)

monday       5000
tuesday      7000
wednesday    6000
thursday     9000
friday       8000
dtype: int64

np.int64(5000)

In [ ]:
s.iloc[0:3] #iloc is integer based lock

monday       5000
tuesday      7000
wednesday    6000
dtype: int64

In [ ]:
s.loc['monday'] #loc is the location based lock (otp will br 5000)

np.int64(5000)

In [ ]:
import pandas as pd
data = {
    "Name": ["Ravi", "Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age": [22,24,None,25,None,26,20,27],
    "City":["Hyderabad","Chennai","Bangalore","Hyderabad","Mumbai",None, "Bangalore","mumbai"],
    "Salary": [30000,40000,28000,50000,35000,45000,None,55000]

}
i = [101,102,103,104,105,106,107,108]
df = pd.DataFrame (data,index = i)
print(df)
df.iloc[0:3] # here the otp comes from 0 to 2 values only
df.loc[101]
df.loc[101:103] #here the output comes from 101 to 103

       Name   Age       City   Salary
101    Ravi  22.0  Hyderabad  30000.0
102   Priya  24.0    Chennai  40000.0
103    Arun   NaN  Bangalore  28000.0
104   Sneha  25.0  Hyderabad  50000.0
105   Kiran   NaN     Mumbai  35000.0
106  Anjali  26.0       None  45000.0
107  Vikram  20.0  Bangalore      NaN
108   Meena  27.0     mumbai  55000.0

      Name   Age       City   Salary
101   Ravi  22.0  Hyderabad  30000.0
102  Priya  24.0    Chennai  40000.0
103   Arun   NaN  Bangalore  28000.0

In [ ]:
#AGGREGATIONS (sum(), min(), max(), count(), mean(), median(), std()
#Aggreagations on series
import pandas as pd
s= pd.Series(
    [5000,7000,6000,9000,8000],
  index=['monday','tuesday','wednesday','thursday','friday',])
print(s)

monday       5000
tuesday      7000
wednesday    6000
thursday     9000
friday       8000
dtype: int64

In [ ]:
s.sum()

np.int64(35000)

In [ ]:
s.min()

5000

In [ ]:
s.max()

9000

In [ ]:
s.count()

np.int64(5)

In [ ]:
s.mean()

np.float64(7000.0)

In [ ]:
s.median()

7000.0

In [ ]:
s.std()

1581.1388300841897

In [ ]:
#Aggreagations on DataFrames
import pandas as pd
data = {
    "Name": ["Ravi", "Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age": [22,24,None,25,None,26,20,27],
    "City":["Hyderabad","Chennai","Bangalore","Hyderabad","Mumbai",None, "Bangalore","mumbai"],
    "Salary": [30000,40000,28000,50000,35000,45000,None,55000]

}
i = [101,102,103,104,105,106,107,108]
df = pd.DataFrame (data,index = i)
print(df)

       Name   Age       City   Salary
101    Ravi  22.0  Hyderabad  30000.0
102   Priya  24.0    Chennai  40000.0
103    Arun   NaN  Bangalore  28000.0
104   Sneha  25.0  Hyderabad  50000.0
105   Kiran   NaN     Mumbai  35000.0
106  Anjali  26.0       None  45000.0
107  Vikram  20.0  Bangalore      NaN
108   Meena  27.0     mumbai  55000.0

In [ ]:
#Concatination
s1 = pd.Series([100,200,300])
s2 = pd.Series([400,500,600])
print(s1)
print(s2)
r = pd.concat([s1,s2],ignore_index=True)#ignore_index=True is the method to avoid indexing number errors
print(r)

0    100
1    200
2    300
dtype: int64
0    400
1    500
2    600
dtype: int64
0    100
1    200
2    300
3    400
4    500
5    600
dtype: int64

In [ ]:
import pandas as pd
data = [25000,28000,32000,None,35000,38000,None,42000,45000,48000]
i = ['01-aug','02-aug','03-aug','04-aug','05-aug','06-aug','07-aug','08-aug','09-aug','10-aug']
s = pd.Series (data,index = i)
print(s)

01-aug    25000.0
02-aug    28000.0
03-aug    32000.0
04-aug        NaN
05-aug    35000.0
06-aug    38000.0
07-aug        NaN
08-aug    42000.0
09-aug    45000.0
10-aug    48000.0
dtype: float64

In [ ]:
#first 5 indexes
s.head(5)

01-aug    25000.0
02-aug    28000.0
03-aug    32000.0
04-aug        NaN
05-aug    35000.0
dtype: float64

In [ ]:
#last 3 indexes
s.tail(3)

08-aug    42000.0
09-aug    45000.0
10-aug    48000.0
dtype: float64

In [ ]:

#find missing values
s.isna()

01-aug    False
02-aug    False
03-aug    False
04-aug     True
05-aug    False
06-aug    False
07-aug     True
08-aug    False
09-aug    False
10-aug    False
dtype: bool

In [ ]:
#count missing values
s.isna().sum()

np.int64(2)

In [ ]:
#replace null values with average values
s.fillna(s.mean())

01-aug    25000.0
02-aug    28000.0
03-aug    32000.0
04-aug    36625.0
05-aug    35000.0
06-aug    38000.0
07-aug    36625.0
08-aug    42000.0
09-aug    45000.0
10-aug    48000.0
dtype: float64

In [ ]:
#display sales greater than 35000
s>35000

01-aug    False
02-aug    False
03-aug    False
04-aug    False
05-aug    False
06-aug     True
07-aug    False
08-aug     True
09-aug     True
10-aug     True
dtype: bool

In [ ]:
#change the sales of 03-aug to 34000
s['03-aug']=34000
print(s)

01-aug    25000.0
02-aug    28000.0
03-aug    34000.0
04-aug        NaN
05-aug    35000.0
06-aug    38000.0
07-aug        NaN
08-aug    42000.0
09-aug    45000.0
10-aug    48000.0
dtype: float64

In [ ]:
#Delete the sales data for 04-aug
s=s.drop('04-aug')
print(s)

01-aug    25000.0
02-aug    28000.0
03-aug    34000.0
05-aug    35000.0
06-aug    38000.0
07-aug        NaN
08-aug    42000.0
09-aug    45000.0
10-aug    48000.0
dtype: float64

In [ ]:
#add sales for 11-aug as 55,000
s['11-aug']=50000
print(s)

01-aug    25000.0
02-aug    28000.0
03-aug    34000.0
05-aug    35000.0
06-aug    38000.0
07-aug        NaN
08-aug    42000.0
09-aug    45000.0
10-aug    48000.0
11-aug    50000.0
dtype: float64

In [ ]:
#total sales
s.sum()

np.float64(295000.0)

In [ ]:
s.mean()

np.float64(36875.0)

In [ ]:
s.max()

48000.0

In [ ]:
s.min()

25000.0

In [ ]:
import pandas as pd
data = [120000,135000,None,150000,165000,None,180000,195000,210000,225000]
i = ['january','february','march','april','may','june','july','august','september','october']
s = pd.Series (data,index = i)
print(s)

january      120000.0
february     135000.0
march             NaN
april        150000.0
may          165000.0
june              NaN
july         180000.0
august       195000.0
september    210000.0
october      225000.0
dtype: float64

In [ ]:
#display first 5 values
s.head(5)

january     120000.0
february    135000.0
march            NaN
april       150000.0
may         165000.0
dtype: float64

In [ ]:
#display last 3 values
s.tail(3)

august       195000.0
september    210000.0
october      225000.0
dtype: float64

In [ ]:
#display jan,mar,may
s[['january', 'march', 'may']]

january    120000.0
march           NaN
may        165000.0
dtype: float64

In [ ]:
#display revenue greater than 170000
s>170000

january      False
february     False
march        False
april        False
may          False
june         False
july          True
august        True
september     True
october       True
dtype: bool

In [ ]:
#find missing values
s.isna()

january      False
february     False
march         True
april        False
may          False
june          True
july         False
august       False
september    False
october      False
dtype: bool

In [ ]:
#count missing values
s.isna().sum()

np.int64(2)

In [ ]:
#fill null values with avg revenue
s.fillna(s.mean())

january      120000.0
february     135000.0
march        172500.0
april        150000.0
may          165000.0
june         172500.0
july         180000.0
august       195000.0
september    210000.0
october      225000.0
dtype: float64

In [ ]:
#change april revenue
s['april']=155000
print(s)

january      120000.0
february     135000.0
march             NaN
april        155000.0
may          165000.0
june              NaN
july         180000.0
august       195000.0
september    210000.0
october      225000.0
dtype: float64

In [ ]:
#Delete feb
s.drop('february')

january      120000.0
march             NaN
april        155000.0
may          165000.0
june              NaN
july         180000.0
august       195000.0
september    210000.0
october      225000.0
dtype: float64

In [ ]:
#Display november with revenue
s['November']=240000
print(s)

january      120000.0
february     135000.0
march             NaN
april        155000.0
may          165000.0
june              NaN
july         180000.0
august       195000.0
september    210000.0
october      225000.0
November     240000.0
dtype: float64

In [ ]:
#find total revenue
s.sum()

np.float64(1380000.0)

In [ ]:
#find average revenue
s.mean()

np.float64(180555.55555555556)

In [ ]:
import pandas as pd
data = [120000,135000,None,150000,165000,None,180000,195000,210000,225000]
i = ['january','february','march','april','may','june','july','august','september','october']
s = pd.Series (data,index = i)
print(s)

january      120000.0
february     135000.0
march             NaN
april        150000.0
may          165000.0
june              NaN
july         180000.0
august       195000.0
september    210000.0
october      225000.0
dtype: float64

In [ ]:
#find min revenue
s.min()

120000.0

In [ ]:
#find max revenue
s.max()

225000.0

In [ ]:
import pandas as pd
data = [120000,135000,None,150000,165000,None,180000,195000,210000,225000]
i = ['january','february','march','april','may','june','july','august','september','october']
s = pd.Series (data,index = i)
print(s)
dec = pd.Series([240000], index=['december'])
r = pd.concat([s, dec])
print(r)

january      120000.0
february     135000.0
march             NaN
april        150000.0
may          165000.0
june              NaN
july         180000.0
august       195000.0
september    210000.0
october      225000.0
dtype: float64
january      120000.0
february     135000.0
march             NaN
april        150000.0
may          165000.0
june              NaN
july         180000.0
august       195000.0
september    210000.0
october      225000.0
december     240000.0
dtype: float64

In [ ]:
#DAY-5 (converting Series to DataFrame)
# to_frame()
import pandas as pd
s=pd.Series(
    [1,2,3,4],
    name='Numbers'
)
s2=pd.Series([9,6,5,8])
s3=pd.Series([12,13,14,15])
df=s.to_frame()

print(df)

    0
0  12
1  13
2  14
3  15

In [ ]:
import pandas as pd
s=pd.Series(
    [1,2,3,4],
    name='Numbers'
)
s2=pd.Series([9,6,5,8])
s3=pd.Series([12,13,14,15])
df=s.to_frame()
print(df)
# Converting Series into Dictionary
d = {
    'Name': s,
    'Age': s2,
    'Marks': s3
}
# Converting Dictionary into DataFrame
df = pd.DataFrame(d)
print(df)

   Numbers
0        1
1        2
2        3
3        4
   Name  Age  Marks
0     1    9     12
1     2    6     13
2     3    5     14
3     4    8     15

In [ ]:
#Renaming the single column
import pandas as pd
s = pd.Series(
    [1,2,3,4],
    name = 'Numbers'
)
df = s.to_frame()
df.columns = ['Digits']
print(df)

   Digits
0       1
1       2
2       3
3       4

In [ ]:
import pandas as pd
s=pd.Series(
    [1,2,3,4],
    name='Numbers'
)
s2=pd.Series([9,6,5,8])
s3=pd.Series([12,13,14,15])
df=s.to_frame()
print(df)
# Converting Series into Dictionary
d = {
    'Name': s,
    'Age': s2,
    'Marks': s3
}
# Converting Dictionary into DataFrame
df = pd.DataFrame(d)
print(df)
df.head(2)

   Numbers
0        1
1        2
2        3
3        4
   Name  Age  Marks
0     1    9     12
1     2    6     13
2     3    5     14
3     4    8     15

   Name  Age  Marks
0     1    9     12
1     2    6     13

In [ ]:
df.tail(2)

   Name  Age  Marks
2     3    5     14
3     4    8     15

In [ ]:
df.isna()

    Name    Age  Marks
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [ ]:
# info() method is used to get information about the DataFrame
import pandas as pd
s = pd.Series(
    [1,2,3,4,5,6,7,8],
    name = 'Numbers'
)
s2 = pd.Series([9,6,5,8,9,10,11])
s3 = pd.Series([12,13,14,15,16,17,18,19,20])

df = s.to_frame()
df ={
"name":s,
"age":s2,
"marks":s3}
df = pd.DataFrame(df)
print(df)
df.info()

   name   age  marks
0   1.0   9.0     12
1   2.0   6.0     13
2   3.0   5.0     14
3   4.0   8.0     15
4   5.0   9.0     16
5   6.0  10.0     17
6   7.0  11.0     18
7   8.0   NaN     19
8   NaN   NaN     20
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      float64
 1   age     7 non-null      float64
 2   marks   9 non-null      int64
dtypes: float64(2), int64(1)
memory usage: 348.0 bytes

In [ ]:
# describe() method is used to get statistical summary of the DataFrame
df.describe()

          name        age      marks
count  8.00000   7.000000   9.000000
mean   4.50000   8.285714  16.000000
std    2.44949   2.138090   2.738613
min    1.00000   5.000000  12.000000
25%    2.75000   7.000000  14.000000
50%    4.50000   9.000000  16.000000
75%    6.25000   9.500000  18.000000
max    8.00000  11.000000  20.000000

In [ ]:
# Selecting a single column
import pandas as pd
s = pd.Series(
    [1,2,3,4,5,6,7,8],
    name='Numbers'
)
s2 = pd.Series([9,6,5,8,9,10,11])
s3 = pd.Series([12,13,14,15,16,17,18,19,20])
df = {
    "name": s,
    "age": s2,
    "marks": s3
}
df = pd.DataFrame(df)
print(df)
df[['name']]

   name   age  marks
0   1.0   9.0     12
1   2.0   6.0     13
2   3.0   5.0     14
3   4.0   8.0     15
4   5.0   9.0     16
5   6.0  10.0     17
6   7.0  11.0     18
7   8.0   NaN     19
8   NaN   NaN     20

   name
0   1.0
1   2.0
2   3.0
3   4.0
4   5.0
5   6.0
6   7.0
7   8.0
8   NaN

In [ ]:
# Selecting the first row
print(df.iloc[0])

name      1.0
age       9.0
marks    12.0
Name: 0, dtype: float64

In [ ]:
## Selecting a row using loc
df.loc[3]

name      4.0
age       8.0
marks    15.0
Name: 3, dtype: float64

In [ ]:
import pandas as pd
data = {
    "Name": ["Ravi", "Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age": [22,24,None,25,None,26,20,27],
    "City":["Hyderabad","Chennai","Bangalore","Hyderabad","Mumbai",None, "Bangalore","mumbai"],
    "Salary": [30000,40000,28000,50000,35000,45000,None,55000]

}
i = [101,102,103,104,105,106,107,108]
df = pd.DataFrame (data,index = i)
print(df)

       Name   Age       City   Salary
101    Ravi  22.0  Hyderabad  30000.0
102   Priya  24.0    Chennai  40000.0
103    Arun   NaN  Bangalore  28000.0
104   Sneha  25.0  Hyderabad  50000.0
105   Kiran   NaN     Mumbai  35000.0
106  Anjali  26.0       None  45000.0
107  Vikram  20.0  Bangalore      NaN
108   Meena  27.0     mumbai  55000.0

In [ ]:
#Select the employees whose Age is greater than 21
age_ = df[df["Age"] > 21]
print(age_)

       Name   Age       City   Salary
101    Ravi  22.0  Hyderabad  30000.0
102   Priya  24.0    Chennai  40000.0
104   Sneha  25.0  Hyderabad  50000.0
106  Anjali  26.0       None  45000.0
108   Meena  27.0     mumbai  55000.0

In [ ]:
#Select the employees whose Salary is greater than 40000
sal_= df[df["Salary"] > 40000]
print(sal_)

       Name   Age       City   Salary
104   Sneha  25.0  Hyderabad  50000.0
106  Anjali  26.0       None  45000.0
108   Meena  27.0     mumbai  55000.0

In [ ]:
#Select the employees who are from Hyderabad
result = df[df["City"] == "Hyderabad"]
print(result)

      Name   Age       City   Salary
101   Ravi  22.0  Hyderabad  30000.0
104  Sneha  25.0  Hyderabad  50000.0

In [ ]:
#Select the employees whose Age is greater than 22 and City is Hyderabad
res = df[
    (df["Age"] > 22) &
    (df["City"] == "Hyderabad")
]
print(res)

      Name   Age       City   Salary
104  Sneha  25.0  Hyderabad  50000.0

In [ ]:
#Select the employees whose Age is greater than 22 or Salary is greater than 40000
data_= df[
    (df["Age"] > 22) |
    (df["Salary"] > 40000)
]
print(data_)

       Name   Age       City   Salary
102   Priya  24.0    Chennai  40000.0
104   Sneha  25.0  Hyderabad  50000.0
106  Anjali  26.0       None  45000.0
108   Meena  27.0     mumbai  55000.0

In [ ]:
#Select the employees whose Salary is less than 40000
any_= df[df["Salary"] < 40000]
print(any_)

      Name   Age       City   Salary
101   Ravi  22.0  Hyderabad  30000.0
103   Arun   NaN  Bangalore  28000.0
105  Kiran   NaN     Mumbai  35000.0

In [ ]:
#Select the employees whose Age is greater than or equal to 25
result = df[df["Age"] >= 25]
print(result)

       Name   Age       City   Salary
104   Sneha  25.0  Hyderabad  50000.0
106  Anjali  26.0       None  45000.0
108   Meena  27.0     mumbai  55000.0

In [ ]:
#Select the employees who are from Bangalore
result = df[df["City"] == "Bangalore"]
print(result)

       Name   Age       City   Salary
103    Arun   NaN  Bangalore  28000.0
107  Vikram  20.0  Bangalore      NaN

In [ ]:
#Aggreagations on DataFrames
import pandas as pd
data = {
    "Name": ["Ravi", "Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age": [22,24,None,25,None,26,20,27],
    "City":["Hyderabad","Chennai","Bangalore","Hyderabad","Mumbai",None, "Bangalore","mumbai"],
    "Salary": [30000,40000,28000,50000,35000,45000,None,55000]

}
i = [101,102,103,104,105,106,107,108]
df = pd.DataFrame (data,index = i)
print(df)

       Name   Age       City   Salary
101    Ravi  22.0  Hyderabad  30000.0
102   Priya  24.0    Chennai  40000.0
103    Arun   NaN  Bangalore  28000.0
104   Sneha  25.0  Hyderabad  50000.0
105   Kiran   NaN     Mumbai  35000.0
106  Anjali  26.0       None  45000.0
107  Vikram  20.0  Bangalore      NaN
108   Meena  27.0     mumbai  55000.0

In [ ]:
df.isna()

      Name    Age   City  Salary
101  False  False  False   False
102  False  False  False   False
103  False   True  False   False
104  False  False  False   False
105  False   True  False   False
106  False  False   True   False
107  False  False  False    True
108  False  False  False   False

In [ ]:
df.isna().sum()

Name      0
Age       2
City      1
Salary    1
dtype: int64

In [ ]:
df.fillna('NR')

       Name   Age       City   Salary
101    Ravi  22.0  Hyderabad  30000.0
102   Priya  24.0    Chennai  40000.0
103    Arun    NR  Bangalore  28000.0
104   Sneha  25.0  Hyderabad  50000.0
105   Kiran    NR     Mumbai  35000.0
106  Anjali  26.0         NR  45000.0
107  Vikram  20.0  Bangalore       NR
108   Meena  27.0     mumbai  55000.0

In [ ]:
df.dropna()

      Name   Age       City   Salary
101   Ravi  22.0  Hyderabad  30000.0
102  Priya  24.0    Chennai  40000.0
104  Sneha  25.0  Hyderabad  50000.0
108  Meena  27.0     mumbai  55000.0

In [ ]:
#DAY-6
#Remove columns containing missing values
df.dropna(axis=1) #axis=1 means columns will be removed which will contain null values

       Name
101    Ravi
102   Priya
103    Arun
104   Sneha
105   Kiran
106  Anjali
107  Vikram
108   Meena

In [ ]:
df.dropna(axis=0) # axis=0 means remove the rows which contain null values
 #if we use inplace means it will change perminently

      Name   Age       City   Salary
101   Ravi  22.0  Hyderabad  30000.0
102  Priya  24.0    Chennai  40000.0
104  Sneha  25.0  Hyderabad  50000.0
108  Meena  27.0     mumbai  55000.0

In [ ]:
import pandas as pd
data = {
    "Name": ["Ravi", "Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age": [22,24,None,25,None,26,20,27],
    "City":["Hyderabad","Chennai","Bangalore","Hyderabad","Mumbai",None, "Bangalore","mumbai"],
    "Salary": [30000,40000,28000,50000,35000,45000,None,55000]

}
i = [101,102,103,104,105,106,107,108]
df = pd.DataFrame (data,index = i)
print(df)

       Name   Age       City   Salary
101    Ravi  22.0  Hyderabad  30000.0
102   Priya  24.0    Chennai  40000.0
103    Arun   NaN  Bangalore  28000.0
104   Sneha  25.0  Hyderabad  50000.0
105   Kiran   NaN     Mumbai  35000.0
106  Anjali  26.0       None  45000.0
107  Vikram  20.0  Bangalore      NaN
108   Meena  27.0     mumbai  55000.0

In [ ]:
#fillna() filling misssing values
#filling specific columns with specific values
df.fillna({
    "Age" : 0,
    "City" : "Unknown"})

       Name   Age       City   Salary
101    Ravi  22.0  Hyderabad  30000.0
102   Priya  24.0    Chennai  40000.0
103    Arun   0.0  Bangalore  28000.0
104   Sneha  25.0  Hyderabad  50000.0
105   Kiran   0.0     Mumbai  35000.0
106  Anjali  26.0    Unknown  45000.0
107  Vikram  20.0  Bangalore      NaN
108   Meena  27.0     mumbai  55000.0

In [ ]:
#filling numeric values with mean
df['Age']=df['Age'].fillna(
    df['Age'].mean())
print(df)

       Name   Age       City   Salary
101    Ravi  22.0  Hyderabad  30000.0
102   Priya  24.0    Chennai  40000.0
103    Arun  24.0  Bangalore  28000.0
104   Sneha  25.0  Hyderabad  50000.0
105   Kiran  24.0     Mumbai  35000.0
106  Anjali  26.0       None  45000.0
107  Vikram  20.0  Bangalore      NaN
108   Meena  27.0     mumbai  55000.0

In [ ]:
import pandas as pd
emp_details = {
    "EmpID":[101,102,103,104,101],
    "City":["Hyderabad","Chennai","Bangalore",None,"Hyderbad"],
    "Experience":[None,4,3,5,2],
    "Age":[25,30,None,35,25]
}
df=pd.DataFrame(emp_details)
print(df)

   EmpID       City  Experience   Age
0    101  Hyderabad         NaN  25.0
1    102    Chennai         4.0  30.0
2    103  Bangalore         3.0   NaN
3    104       None         5.0  35.0
4    101   Hyderbad         2.0  25.0

In [ ]:
df.isna()

   EmpID   City  Experience    Age
0  False  False        True  False
1  False  False       False  False
2  False  False       False   True
3  False   True       False  False
4  False  False       False  False

In [ ]:
df.isna().sum()

EmpID         0
City          1
Experience    1
Age           1
dtype: int64

In [ ]:
#missing values in city fill with unknown, in exp fill with 0, in age fill with median...
df.fillna({
    "City" : "Unknown",
    "Experience": 0
    })

   EmpID       City  Experience   Age
0    101  Hyderabad         0.0  25.0
1    102    Chennai         4.0  30.0
2    103  Bangalore         3.0   NaN
3    104    Unknown         5.0  35.0
4    101   Hyderbad         2.0  25.0

In [ ]:
df['Age']=df['Age'].fillna(
    df['Age'].median())
print(df)

   EmpID       City  Experience   Age
0    101  Hyderabad         NaN  25.0
1    102    Chennai         4.0  30.0
2    103  Bangalore         3.0  27.5
3    104       None         5.0  35.0
4    101   Hyderbad         2.0  25.0

In [ ]:
df["salary"]=[2000,1500,1000,None,12000]
print(df)

   EmpID       City  Experience   Age   salary
0    101  Hyderabad         NaN  25.0   2000.0
1    102    Chennai         4.0  30.0   1500.0
2    103  Bangalore         3.0  27.5   1000.0
3    104       None         5.0  35.0      NaN
4    101   Hyderbad         2.0  25.0  12000.0

In [ ]:
import pandas as pd
emp_details = {
    "EmpID":[101,102,103,104,101],
    "City":["Hyderabad","Chennai","Bangalore",None,"Hyderbad"],
    "Experience":[None,4,3,5,2],
    "Age":[25,30,None,35,25]
}
df=pd.DataFrame(emp_details)
print(df)

   EmpID       City  Experience   Age
0    101  Hyderabad         NaN  25.0
1    102    Chennai         4.0  30.0
2    103  Bangalore         3.0   NaN
3    104       None         5.0  35.0
4    101   Hyderbad         2.0  25.0

In [ ]:
# Rename EmpId = Employee_id
df.rename(columns={"EmpID": "Employee_id"}, inplace=True)
print(df)

   Employee_id       City  Experience   Age
0          101  Hyderabad         NaN  25.0
1          102    Chennai         4.0  30.0
2          103  Bangalore         3.0   NaN
3          104       None         5.0  35.0
4          101   Hyderbad         2.0  25.0

In [ ]:
# Increase the Age by 1
df["Age"] = df["Age"] + 1
print(df)

   Employee_id       City  Experience   Age
0          101  Hyderabad         NaN  26.0
1          102    Chennai         4.0  31.0
2          103  Bangalore         3.0   NaN
3          104       None         5.0  36.0
4          101   Hyderbad         2.0  26.0

In [ ]:
df["salary"] = [2000,1500,1000,None,12000]
print(df)

   Employee_id       City  Experience   Age   salary
0          101  Hyderabad         NaN  26.0   2000.0
1          102    Chennai         4.0  31.0   1500.0
2          103  Bangalore         3.0   NaN   1000.0
3          104       None         5.0  36.0      NaN
4          101   Hyderbad         2.0  26.0  12000.0

In [ ]:
#new column bonus every person get 10%hike
df["Bonus"]=(df["salary"]*0.10)
print(df)

   Employee_id       City  Experience   Age   salary   Bonus
0          101  Hyderabad         NaN  26.0   2000.0   200.0
1          102    Chennai         4.0  31.0   1500.0   150.0
2          103  Bangalore         3.0   NaN   1000.0   100.0
3          104       None         5.0  36.0      NaN     NaN
4          101   Hyderbad         2.0  26.0  12000.0  1200.0

In [ ]:
# Deleting a column
# axis=1 → operation on columns
# axis=0 → operation on rows
df.drop(
    'Bonus',
    axis=1,
    inplace=True
)
print(df)

   Employee_id       City  Experience   Age   salary
0          101  Hyderabad         NaN  26.0   2000.0
1          102    Chennai         4.0  31.0   1500.0
2          103  Bangalore         3.0   NaN   1000.0
3          104       None         5.0  36.0      NaN
4          101   Hyderbad         2.0  26.0  12000.0

In [ ]:
# Deleting salary column
df.drop(columns=['salary'], inplace=True)
print(df)

   Employee_id       City  Experience   Age
0          101  Hyderabad         NaN  26.0
1          102    Chennai         4.0  31.0
2          103  Bangalore         3.0   NaN
3          104       None         5.0  36.0
4          101   Hyderbad         2.0  26.0

In [ ]:
print(df.columns)

Index(['Employee_id', 'City', 'Experience', 'Age'], dtype='object')

In [ ]:
import pandas as pd
emp_details = {
    "EmpID":[101,102,103,104,101],
    "City":["Hyderabad","Chennai","Bangalore",None,"Hyderbad"],
    "Experience":[None,4,3,5,2],
    "Age":[25,30,None,35,25]
}
df=pd.DataFrame(emp_details)
print(df)

   EmpID       City  Experience   Age
0    101  Hyderabad         NaN  25.0
1    102    Chennai         4.0  30.0
2    103  Bangalore         3.0   NaN
3    104       None         5.0  35.0
4    101   Hyderbad         2.0  25.0

In [ ]:
# Adding a new row
df.loc[len(df)] = (105, 'Bihar', 5, 22)
print(df)

   Employee_id       City  Experience   Age
0          101  Hyderabad         NaN  26.0
1          102    Chennai         4.0  31.0
2          103  Bangalore         3.0   NaN
3          104       None         5.0  36.0
4          101   Hyderbad         2.0  26.0
5          105      Bihar         5.0  22.0

In [ ]:
# Deleting a row
df.drop(2, axis=0, inplace=True)
print(df)

   Employee_id       City  Experience   Age
0          101  Hyderabad         NaN  26.0
1          102    Chennai         4.0  31.0
3          104       None         5.0  36.0
4          101   Hyderbad         2.0  26.0
5          105      Bihar         5.0  22.0

In [ ]:
#Groupby
import pandas as pd
emp_details = {
    "EmpID":[101,102,103,104,101],
    "City":["Hyderabad","Chennai","Bangalore",None,"Hyderbad"],
    "Experience":[None,4,3,5,2],
    "Age":[25,30,None,35,25]
}
df=pd.DataFrame(emp_details)
print(df)
df.groupby('City')['Age'].min() #city is a method so it is in (), age is a column so it in []...

   EmpID       City  Experience   Age
0    101  Hyderabad         NaN  25.0
1    102    Chennai         4.0  30.0
2    103  Bangalore         3.0   NaN
3    104       None         5.0  35.0
4    101   Hyderbad         2.0  25.0

City
Bangalore     NaN
Chennai      30.0
Hyderabad    25.0
Hyderbad     25.0
Name: Age, dtype: float64

In [ ]:
df.groupby('City')['Age'].max()

City
Bangalore     NaN
Chennai      30.0
Hyderabad    25.0
Hyderbad     25.0
Name: Age, dtype: float64

In [ ]:
df.groupby('City')['Age'].mean()

City
Bangalore     NaN
Chennai      30.0
Hyderabad    25.0
Hyderbad     25.0
Name: Age, dtype: float64

In [ ]:
df.groupby('City')['Age'].sum()
df.groupby('City')['Age'].count()

City
Bangalore    0
Chennai      1
Hyderabad    1
Hyderbad     1
Name: Age, dtype: int64

In [ ]:
import pandas as p
data = {
    "Name": ["Ravi", "Priya", "Arun", "Sneha", "Kiran", "Anjali", "Vikram", "Meena"],
    "Age": [22, 24, 21, 25, 23, 26, 20, 27],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad",
             "Mumbai", "Chennai", "Bangalore", "Mumbai"],
    "Salary": [30000, 40000, 28000, 50000, 35000, 45000, 25000, 55000]
}

df = pd.DataFrame(data)
print(df)

     Name  Age       City  Salary
0    Ravi   22  Hyderabad   30000
1   Priya   24    Chennai   40000
2    Arun   21  Bangalore   28000
3   Sneha   25  Hyderabad   50000
4   Kiran   23     Mumbai   35000
5  Anjali   26    Chennai   45000
6  Vikram   20  Bangalore   25000
7   Meena   27     Mumbai   55000

In [ ]:
#2) Show only Name column
print(df["Name"])

0      Ravi
1     Priya
2      Arun
3     Sneha
4     Kiran
5    Anjali
6    Vikram
7     Meena
Name: Name, dtype: object

In [ ]:
#3)Show only Name and Salary
print(df[["Name", "Salary"]])

     Name  Salary
0    Ravi   30000
1   Priya   40000
2    Arun   28000
3   Sneha   50000
4   Kiran   35000
5  Anjali   45000
6  Vikram   25000
7   Meena   55000

In [ ]:
#4)Employees older than 23
print(df[df["Age"] > 23])

     Name  Age       City  Salary
1   Priya   24    Chennai   40000
3   Sneha   25  Hyderabad   50000
5  Anjali   26    Chennai   45000
7   Meena   27     Mumbai   55000

In [ ]:
#5)Employees earning more than 40000
print(df[df["Salary"] > 40000])

     Name  Age       City  Salary
3   Sneha   25  Hyderabad   50000
5  Anjali   26    Chennai   45000
7   Meena   27     Mumbai   55000

In [ ]:
#6)Employees from Chennai
print(df[df["City"] == "Chennai"])

     Name  Age     City  Salary
1   Priya   24  Chennai   40000
5  Anjali   26  Chennai   45000

In [ ]:
#7)Age > 22 and Salary > 35000
print(df[(df["Age"] > 22) & (df["Salary"] > 35000)])

     Name  Age       City  Salary
1   Priya   24    Chennai   40000
3   Sneha   25  Hyderabad   50000
5  Anjali   26    Chennai   45000
7   Meena   27     Mumbai   55000

In [ ]:
#8)City is Mumbai or Bangalore
print(df[(df["City"] == "Mumbai") | (df["City"] == "Bangalore")])

     Name  Age       City  Salary
2    Arun   21  Bangalore   28000
4   Kiran   23     Mumbai   35000
6  Vikram   20  Bangalore   25000
7   Meena   27     Mumbai   55000

In [ ]:
#9)Name and Salary where Salary > 30000
print(df[df["Salary"] > 30000][["Name", "Salary"]])

     Name  Salary
1   Priya   40000
3   Sneha   50000
4   Kiran   35000
5  Anjali   45000
7   Meena   55000

In [ ]:
#10) 2nd, 3rd, 4th employees
print(df.iloc[1:4])

    Name  Age       City  Salary
1  Priya   24    Chennai   40000
2   Arun   21  Bangalore   28000
3  Sneha   25  Hyderabad   50000

In [ ]:
#11) First 4 employees, only Name and Age
print(df.loc[0:3, ["Name", "Age"]])

    Name  Age
0   Ravi   22
1  Priya   24
2   Arun   21
3  Sneha   25

In [ ]:
# 12)1st, 4th, 7th employees
print(df.iloc[[0, 3, 6]])

     Name  Age       City  Salary
0    Ravi   22  Hyderabad   30000
3   Sneha   25  Hyderabad   50000
6  Vikram   20  Bangalore   25000

In [ ]:
#13)Employees with index 2 to 5
print(df.loc[2:5])

     Name  Age       City  Salary
2    Arun   21  Bangalore   28000
3   Sneha   25  Hyderabad   50000
4   Kiran   23     Mumbai   35000
5  Anjali   26    Chennai   45000

In [ ]:
#14)Rename all columns
rename_= df.rename(columns={"Name": "Employee_Name", "Age": "Employee_Age",
                          "City": "Location", "Salary": "Monthly_Salary"})
print(rename_)

  Employee_Name  Employee_Age   Location  Monthly_Salary
0          Ravi            22  Hyderabad           30000
1         Priya            24    Chennai           40000
2          Arun            21  Bangalore           28000
3         Sneha            25  Hyderabad           50000
4         Kiran            23     Mumbai           35000
5        Anjali            26    Chennai           45000
6        Vikram            20  Bangalore           25000
7         Meena            27     Mumbai           55000

In [ ]:
#15)Age between 22 and 26, show Name, City, Salary
print(df[(df["Age"] >= 22) & (df["Age"] <= 26)][["Name", "City", "Salary"]])

     Name       City  Salary
0    Ravi  Hyderabad   30000
1   Priya    Chennai   40000
3   Sneha  Hyderabad   50000
4   Kiran     Mumbai   35000
5  Anjali    Chennai   45000

In [ ]:
#DAY-7 (GROUP BY)
import pandas as pd
emp_details = {
    "EmpID":[101,102,103,104,101],
    "City":["Hyderabad","Chennai","Bangalore","Vizag","Hyderbad"],
    "Experience":[3,4,3,5,2],
    "Age":[25,30,22,35,25]
}
df=pd.DataFrame(emp_details)
print(df)

   EmpID       City  Experience  Age
0    101  Hyderabad           3   25
1    102    Chennai           4   30
2    103  Bangalore           3   22
3    104      Vizag           5   35
4    101   Hyderbad           2   25

In [ ]:
#Basic Groupby()
df.groupby('City')['Age'].mean()

City
Bangalore    22.0
Chennai      30.0
Hyderabad    25.0
Hyderbad     25.0
Vizag        35.0
Name: Age, dtype: float64

In [ ]:
#Groupby on single column with multiple aggregations
df.groupby('City')['Age'].agg(['mean','max','min'])

           mean  max  min
City
Bangalore  22.0   22   22
Chennai    30.0   30   30
Hyderabad  25.0   25   25
Hyderbad   25.0   25   25
Vizag      35.0   35   35

In [ ]:
#Groupby On Multiple Columns With Multiple Aggregations
df.groupby('City').agg({
    'Age':['mean','max'],
    'Experience':['sum','count']
})

            Age     Experience
           mean max        sum count
City
Bangalore  22.0  22          3     1
Chennai    30.0  30          4     1
Hyderabad  25.0  25          3     1
Hyderbad   25.0  25          2     1
Vizag      35.0  35          5     1

In [ ]:
# Merges and Joins (Left,right,inner,full outer)
df1=pd.DataFrame({
    'ID':[1,2,3],
    'Name':['A','B','c']
})
df2=pd.DataFrame({
    'ID': [1,2,3],
    'Salary':[1000,2000,3000]
})
print(df1)
print(df2)

   ID Name
0   1    A
1   2    B
2   3    c
   ID  Salary
0   1    1000
1   2    2000
2   3    3000

In [ ]:
merged=pd.merge(df1,df2,on='ID',how='inner')
print(merged)

   ID Name  Salary
0   1    A    1000
1   2    B    2000
2   3    c    3000

In [ ]:
merged=pd.merge(df1,df2,on='ID',how='outer')
print(merged)

   ID Name  Salary
0   1    A    1000
1   2    B    2000
2   3    c    3000

In [ ]:
merged=pd.merge(df1,df2,on='ID',how='left')
print(merged)

   ID Name  Salary
0   1    A    1000
1   2    B    2000
2   3    c    3000

In [ ]:
merged=pd.merge(df1,df2,on='ID',how='right')
print(merged)

   ID Name  Salary
0   1    A    1000
1   2    B    2000
2   3    c    3000

In [ ]:
combined=pd.concat(
    [df1,df2],
    axis=0,
    ignore_index=True)

In [ ]:
combined=pd.concat(
    [df1,df2],
    axis=1,
    ignore_index=True)

In [ ]:
#Working on CSV Files
import pandas as pd
df=pd.read_csv('/content/sample_data/california_housing_train.csv')
print(df)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0
1        -114.47     34.40                19.0       7650.0          1901.0
2        -114.56     33.69                17.0        720.0           174.0
3        -114.57     33.64                14.0       1501.0           337.0
4        -114.57     33.57                20.0       1454.0           326.0
...          ...       ...                 ...          ...             ...
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
0          1015.0       472.0         1.4936             66900.0
1          1129.0       463.0         1.8200             80100.0
2           333.0       117.0         1.6509             85700.0
3           515.0       226.0         3.1917             73400.0
4           624.0       262.0         1.9250             65500.0
...           ...         ...            ...                 ...
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

[17000 rows x 9 columns]

In [ ]:
print(df.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0
1    -114.47     34.40                19.0       7650.0          1901.0
2    -114.56     33.69                17.0        720.0           174.0
3    -114.57     33.64                14.0       1501.0           337.0
4    -114.57     33.57                20.0       1454.0           326.0

   population  households  median_income  median_house_value
0      1015.0       472.0         1.4936             66900.0
1      1129.0       463.0         1.8200             80100.0
2       333.0       117.0         1.6509             85700.0
3       515.0       226.0         3.1917             73400.0
4       624.0       262.0         1.9250             65500.0

In [ ]:
print(df.tail())

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16995    -124.26     40.58                52.0       2217.0           394.0
16996    -124.27     40.69                36.0       2349.0           528.0
16997    -124.30     41.84                17.0       2677.0           531.0
16998    -124.30     41.80                19.0       2672.0           552.0
16999    -124.35     40.54                52.0       1820.0           300.0

       population  households  median_income  median_house_value
16995       907.0       369.0         2.3571            111400.0
16996      1194.0       465.0         2.5179             79000.0
16997      1244.0       456.0         3.0313            103600.0
16998      1298.0       478.0         1.9797             85800.0
16999       806.0       270.0         3.0147             94600.0

In [ ]:
print(df.shape)

(17000, 9)

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB
None

In [ ]:
print(df.describe())

          longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000
mean    -119.562108     35.625225           28.589353   2643.664412
std        2.005166      2.137340           12.586937   2179.947071
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.790000     33.930000           18.000000   1462.000000
50%     -118.490000     34.250000           29.000000   2127.000000
75%     -118.000000     37.720000           37.000000   3151.250000
max     -114.310000     41.950000           52.000000  37937.000000

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000
mean       539.410824   1429.573941    501.221941       3.883578
std        421.499452   1147.852959    384.520841       1.908157
min          1.000000      3.000000      1.000000       0.499900
25%        297.000000    790.000000    282.000000       2.566375
50%        434.000000   1167.000000    409.000000       3.544600
75%        648.250000   1721.000000    605.250000       4.767000
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        17000.000000
mean        207300.912353
std         115983.764387
min          14999.000000
25%         119400.000000
50%         180400.000000
75%         265000.000000
max         500001.000000

In [ ]:
#DAY-8
#Working on excel Files(read and write)
import pandas as pd
df=pd.read_excel('/file_example_XLS_100.xls')
sheet= "sheet1"
print(df)

      0 First Name   Last Name  Gender        Country  Age        Date    Id
0     1      Dulce       Abril  Female  United States   32  15/10/2017  1562
1     2       Mara   Hashimoto  Female  Great Britain   25  16/08/2016  1582
2     3     Philip        Gent    Male         France   36  21/05/2015  2587
3     4   Kathleen      Hanner  Female  United States   25  15/10/2017  3549
4     5    Nereida     Magwood  Female  United States   58  16/08/2016  2468
..  ...        ...         ...     ...            ...  ...         ...   ...
95   96       Roma  Lafollette  Female  United States   34  15/10/2017  2654
96   97     Felisa        Cail  Female  United States   28  16/08/2016  6525
97   98   Demetria       Abbey  Female  United States   32  21/05/2015  3265
98   99     Jeromy        Danz    Male  United States   39  15/10/2017  3265
99  100   Rasheeda      Alkire  Female  United States   29  16/08/2016  6125

[100 rows x 8 columns]

In [ ]:
print(df.head())

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468

In [ ]:
print(df.tail())

      0 First Name   Last Name  Gender        Country  Age        Date    Id
95   96       Roma  Lafollette  Female  United States   34  15/10/2017  2654
96   97     Felisa        Cail  Female  United States   28  16/08/2016  6525
97   98   Demetria       Abbey  Female  United States   32  21/05/2015  3265
98   99     Jeromy        Danz    Male  United States   39  15/10/2017  3265
99  100   Rasheeda      Alkire  Female  United States   29  16/08/2016  6125

In [ ]:
print(df.shape)

(100, 8)

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   0           100 non-null    int64
 1   First Name  100 non-null    object
 2   Last Name   100 non-null    object
 3   Gender      100 non-null    object
 4   Country     100 non-null    object
 5   Age         100 non-null    int64
 6   Date        100 non-null    object
 7   Id          100 non-null    int64
dtypes: int64(3), object(5)
memory usage: 6.4+ KB
None

In [ ]:
print(df.describe())

                0         Age           Id
count  100.000000  100.000000   100.000000
mean    50.500000   33.260000  4717.720000
std     29.011492    8.391458  2379.081421
min      1.000000   21.000000  1258.000000
25%     25.750000   26.000000  2587.000000
50%     50.500000   32.000000  3574.000000
75%     75.250000   38.000000  6540.000000
max    100.000000   58.000000  9654.000000

In [ ]:
df.min()

0                      1
First Name         Angel
Last Name          Abbey
Gender            Female
Country           France
Age                   21
Date          15/10/2017
Id                  1258
dtype: object

In [ ]:
df.max()

0                       100
First Name        Willodean
Last Name         Zabriskie
Gender                 Male
Country       United States
Age                      58
Date             21/05/2015
Id                     9654
dtype: object

In [ ]:
#CLEANING DATA(Missing values,incorrect,.....)
#Incorrect
import pandas as pd
data={
    "EmpID":[101,102,103,104,105,106,107,108,109,110,110],
    "Name":["Ravi","PRIYA","Arun","sneha","Kiran","ANJALI","Vikram","meena","RAHUL","Sneha","Sneha"],
    "City":["Hyderabad","Hyderabad","CHENNAI","Chennai","Bangalore","BANGALORE","Mumbai","mumbai","Delhi","Hyderabad","Hyderabad"],
    "Salary":[30000,40000,35000,45000,32000,50000,38000,42000,36000,45000,45000]
}
df=pd.DataFrame(data)
print(df)

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI   35000
3     104   sneha    Chennai   45000
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   Sneha  Hyderabad   45000
10    110   Sneha  Hyderabad   45000

In [ ]:
#DUPLICATE VALUES(complete row must be same)
#To find Duplicated values
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [ ]:
#To count duplicate values
df.duplicated().sum()

np.int64(1)

In [ ]:
#To display the actual duplicate row
duplicates=df[df.duplicated()]
print(duplicates)

    EmpID   Name       City  Salary
10    110  Sneha  Hyderabad   45000

In [ ]:
#To find all rows involved in a duplicate
duplicates=df[df.duplicated(keep=False)]
print(duplicates)

    EmpID   Name       City  Salary
9     110  Sneha  Hyderabad   45000
10    110  Sneha  Hyderabad   45000

In [ ]:
#To find sum of duplicate rows
d=df[df.duplicated()]
total=d["Salary"].sum()
print(total)

45000

In [ ]:
#To find sum of duplicate rows
d=df[df.duplicated(keep=False)] #keep=False means to find total sum of all duplicates
total=d["Salary"].sum()
print(total)

90000

In [ ]:
#To identify the duplicates to the specific column
df["EmpID"].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
Name: EmpID, dtype: bool

In [ ]:
df["Salary"].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
Name: Salary, dtype: bool

In [ ]:
df["City"].duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
Name: City, dtype: bool

In [ ]:
#To identify the duplicates to the specific Row
df[df["EmpID"].duplicated()]

    EmpID   Name       City  Salary
10    110  Sneha  Hyderabad   45000

In [ ]:
#or use code
df[df["EmpID"].duplicated()]
duplicates=df[df["EmpID"].duplicated()]
print(duplicates)

    EmpID   Name       City  Salary
10    110  Sneha  Hyderabad   45000

In [ ]:
#find all records with duplicates empid's
df[df["EmpID"].duplicated()]
duplicates=df[df["EmpID"].duplicated(keep=False)] #EmpId is the primary key
print(duplicates)

    EmpID   Name       City  Salary
9     110  Sneha  Hyderabad   45000
10    110  Sneha  Hyderabad   45000

In [ ]:
#Find duplicate Names
df[df["Name"].duplicated()]

    EmpID   Name       City  Salary
10    110  Sneha  Hyderabad   45000

In [ ]:
#DROP
# DUPLICATES (from here we use duplicates not duplicated)
df=df.drop_duplicates()
print(df)

   EmpID    Name       City  Salary
0    101    Ravi  Hyderabad   30000
1    102   PRIYA  Hyderabad   40000
2    103    Arun    CHENNAI   35000
3    104   sneha    Chennai   45000
4    105   Kiran  Bangalore   32000
5    106  ANJALI  BANGALORE   50000
6    107  Vikram     Mumbai   38000
7    108   meena     mumbai   42000
8    109   RAHUL      Delhi   36000
9    110   Sneha  Hyderabad   45000

In [ ]:
import pandas as pd
data={
    "EmpID":[101,102,103,104,105,106,107,108,109,110,110],
    "Name":["Ravi","PRIYA","Arun","sneha","Kiran","ANJALI","Vikram","meena","RAHUL","Sneha","Sneha"],
    "City":["Hyderabad","Hyderabad","CHENNAI","Chennai","Bangalore","BANGALORE","Mumbai","mumbai","Delhi","Hyderabad","Hyderabad"],
    "Salary":[30000,40000,35000,45000,32000,50000,38000,42000,36000,45000,45000]
}
df=pd.DataFrame(data)
print(df)

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI   35000
3     104   sneha    Chennai   45000
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   Sneha  Hyderabad   45000
10    110   Sneha  Hyderabad   45000

In [ ]:
#to drop specific duplicate
df=df.drop_duplicates(keep="last") #It remains last duplicate
print(df)

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI   35000
3     104   sneha    Chennai   45000
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
10    110   Sneha  Hyderabad   45000

In [ ]:
import pandas as pd
data={
    "EmpID":[101,102,103,104,105,106,107,108,109,110,110],
    "Name":["Ravi","PRIYA","Arun","sneha","Kiran","ANJALI","Vikram","meena","RAHUL","Sneha","Sneha"],
    "City":["Hyderabad","Hyderabad","CHENNAI","Chennai","Bangalore","BANGALORE","Mumbai","mumbai","Delhi","Hyderabad","Hyderabad"],
    "Salary":[30000,40000,35000,45000,32000,50000,38000,42000,36000,45000,45000]
}
df=pd.DataFrame(data)
print(df)

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI   35000
3     104   sneha    Chennai   45000
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   Sneha  Hyderabad   45000
10    110   Sneha  Hyderabad   45000

In [ ]:
#to drop specific duplicate
df=df.drop_duplicates(keep="first")
print(df)

   EmpID    Name       City  Salary
0    101    Ravi  Hyderabad   30000
1    102   PRIYA  Hyderabad   40000
2    103    Arun    CHENNAI   35000
3    104   sneha    Chennai   45000
4    105   Kiran  Bangalore   32000
5    106  ANJALI  BANGALORE   50000
6    107  Vikram     Mumbai   38000
7    108   meena     mumbai   42000
8    109   RAHUL      Delhi   36000
9    110   Sneha  Hyderabad   45000